version: "3.9"

services:

  backend:
    build: .
    container_name: agenda-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - .:/app
      - ./data:/app/data

    depends_on:
      - mock-api

    restart: unless-stopped

  mock-api:
    build: .

    container_name: agenda-mock-api

    command: python mock_api.py

    ports:
      - "5001:5001"

    volumes:
      - .:/app

    restart: unless-stopped